"""version0.1

Revision ID: 26c87cdec0f3
Revises: 
Create Date: 2022-11-10 01:49:00.448082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26c87cdec0f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('flat_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('flats')
    # ### end Alembic commands ###
